### PR TITLE
Snapshot 21w19a

### PR DESCRIPTION
**Pull request by LemonCaramel**
This PR is porting your BungeeCord Snapshot Patch to Waterfall.

I don't know if this works well. 😢 

I'm always getting help from your patch. Thank you!

### CODE REVIEW

**Comment by LemonCaramel** [comment]
It is now thought that everything will work normally.

**Comment by compieter-gh** [comment]
@LemonCaramel Thank you!

**Comment by ChristianDobbie** [comment]
This PR has been working great with Snapshot 21w10a & ViaVersion-DEV although I haven't been able to test it with a pure 21w10a vanilla server as FabricProxy hasn't been updated/I can't get it to work without Mixin errors.

**Comment by LemonCaramel** [comment]
fixed it 
thank you for letting me know

**Comment by LemonCaramel** [comment]
click miss 😢

**Comment by LemonCaramel** [comment]
Added Minecraft 1.17(21w19a) support for [BungeeCord](https://github.com/SpigotMC/BungeeCord/commit/f0908b663f868ef5fe1f3ac8c81a29827cd6abe1) & [Waterfall](https://github.com/PaperMC/Waterfall/commit/fea7ec356dba6c6ac28819ff11be604af6eb484e).
BungeeCord has all the content(? code?) that applies in this patch.

There is no point in opening this PR anymore.
If 21w20a (or later) is not supported for BungeeCord, this PR will be reopened.

**Pull request closed without merging**
